### ISSUE TITLE
NextJS build fails on Vercel

### ISSUE THREAD

**Issue by martinnormark** [Swizec/useAuth#120]
I have a minimal NextJS app configured with `useAuth` and `Auth0` as provider.

The build fails when running on Vercel.

Not sure if I am doing things wrong, but the build completes successfully when running it locally using `next build`.

```jsx

import { AuthConfig, Providers } from "react-use-auth";
import Head from 'next/head'
import { useRouter } from "next/router";

import '../styles/globals.css'
import Layout from './_layout/Layout'

function MyApp({ Component, pageProps }) {
  const router = useRouter();

  return (
    <>
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthConfig
          authProvider={Providers.Auth0}
          navigate={(url) => router.push(url)}
          params={{
              domain: process.env.NEXT_PUBLIC_AUTH0_DOMAIN,
              clientID: process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID
          }}
      />
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  )
}

export default MyApp
```

### Error
```

09:18:04.383 | Failed to compile.
-- | --
09:18:04.383 | ModuleNotFoundError: Module not found: Error: Can't resolve 'netlify-identity-widget' in '/vercel/workpath0/node_modules/react-use-auth/dist'
09:18:04.383 | > Build error occurred
09:18:04.384 | Error: > Build failed because of webpack errors
09:18:04.384 | at build (/vercel/workpath0/node_modules/next/dist/build/index.js:15:918)
09:18:04.384 | at runMicrotasks (<anonymous>)
09:18:04.384 | at processTicksAndRejections (internal/process/task_queues.js:97:5)
09:18:04.414 | Error: Command "next build --debug" exited with 1
```

### Full build log
```
09:14:02.075  	Cloning github.com/martinnormark/mortimer-nextjs (Branch: master, Commit: d94e474)
09:14:03.276  	Cloning completed in 1201ms
09:14:03.279  	Analyzing source code...
09:14:04.021  	Installing build runtime...
09:14:04.473  	Build runtime installed: 451.812ms
09:14:05.387  	Installing dependencies...
09:14:05.840  	npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
09:14:16.176  	> sharp@0.26.2 install /vercel/workpath0/node_modules/sharp
09:14:16.176  	> (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
09:14:16.330  	info sharp Using cached /vercel/.npm/_libvips/libvips-8.10.0-linux-x64.tar.br
09:14:17.364  	> @ampproject/toolbox-optimizer@2.7.0-alpha.1 postinstall /vercel/workpath0/node_modules/@ampproject/toolbox-optimizer
09:14:17.364  	> node lib/warmup.js
09:14:17.868  	[7mAMP OPTIMIZER[0m Downloaded latest AMP runtime data.
09:14:18.305  	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
09:14:18.305  	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
09:14:18.312  	npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
09:14:18.313  	npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
09:14:18.315  	added 872 packages from 477 contributors in 12.504s
09:14:18.654  	50 packages are looking for funding
09:14:18.654  	  run `npm fund` for details
09:14:18.684  	Running "npm run build"
09:14:18.878  	> nextjs@0.1.0 build /vercel/workpath0
09:14:18.878  	> next build
09:14:19.544  	info  - Creating an optimized production build...
09:14:19.560  	Attention: Next.js now collects completely anonymous telemetry regarding usage.
09:14:19.560  	This information is used to shape Next.js' roadmap and prioritize features.
09:14:19.560  	You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
09:14:19.560  	https://nextjs.org/telemetry
09:14:25.091  	Failed to compile.
09:14:25.091  	ModuleNotFoundError: Module not found: Error: Can't resolve 'netlify-identity-widget' in '/vercel/workpath0/node_modules/react-use-auth/dist'
09:14:25.091  	> Build error occurred
09:14:25.092  	Error: > Build failed because of webpack errors
09:14:25.092  	    at build (/vercel/workpath0/node_modules/next/dist/build/index.js:15:918)
09:14:25.092  	    at runMicrotasks (<anonymous>)
09:14:25.092  	    at processTicksAndRejections (internal/process/task_queues.js:97:5)
09:14:25.124  	npm ERR! code ELIFECYCLE
09:14:25.124  	npm ERR! errno 1
09:14:25.129  	npm ERR! nextjs@0.1.0 build: `next build`
09:14:25.129  	npm ERR! Exit status 1
09:14:25.129  	npm ERR! 
09:14:25.129  	npm ERR! Failed at the nextjs@0.1.0 build script.
09:14:25.129  	npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
09:14:25.137  	npm ERR! A complete log of this run can be found in:
09:14:25.137  	npm ERR!     /vercel/.npm/_logs/2020-12-11T08_14_25_130Z-debug.log
09:14:25.141  	Error: Command "npm run build" exited with 1
09:14:27.289  	Done with "package.json"
```

**Comment by Swizec** [comment]
Related to this issue: https://github.com/Swizec/useAuth/pull/119

You can install `netlify-identity-widget` to resolve this for now.
